### ISSUE TITLE
Check certificate validity

### ISSUE THREAD

**Issue by jirihelmich** [MewsSystems/fiscalization-czechia#11]
https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2.verify(v=vs.110).aspx

**Comment by KaliCZ** [comment]
We migrated the whole project to a [new repo](https://github.com/MewsSystems/fiscalizations). There's no demand for explicit validating of certificates, so if anyone needs this, pls reopen the issue there.
