### ISSUE TITLE
Strange certifcate disposal

### ISSUE THREAD

**Issue by jeancz** [MewsSystems/fiscalization-czechia#17]
Investigation around issue #15 led me to the physical "temporary" keys location. Which is in our case at %APPDATA%\Microsoft\Crypto\RSA\User SID\ . I have noticed, that there remains lot of old temporary keys.

Am I alone?

In spite of it could be done automatically...

> X509Certificate2 implements the IDisposable interface starting with the .NET Framework 4.6; in previous versions of the .NET Framework, the X509Certificate2 class does not implement this interface, and therefore the Dispose method does not exist.

I have tried add dispose() method. Now looks it good for me. The keys there no longer remain.

My modification:
```
            foreach (var certificate in certificateCollection)
            {
                if (!certificate.HasPrivateKey)
                {
                    continue;
                }

                var key = certificate.PrivateKey as RSACryptoServiceProvider;
                var exportParameters = key.ExportParameters(includePrivateParameters: true);
                var cspParameters = new CspParameters
                {
                    ProviderName = "Microsoft Enhanced RSA and AES Cryptographic Provider",
                };
                var result = new RSACryptoServiceProvider(cspParameters);
                result.ImportParameters(exportParameters);
                certificate.Dispose();
                return result;
            }
```

**Comment by KaliCZ** [comment]
@jeancz We migrated the whole project to a [new repo](https://github.com/MewsSystems/fiscalizations). It now targets .net standard. I believe that the issue is not present anymore. If yes, pls reopen the issue in the new repo.
