### ISSUE TITLE
Certificate issue on shared hosting

### ISSUE THREAD

**Issue by pavelstaro** [MewsSystems/fiscalization-czechia#22]
When I use this library on shared hosting , I'm not capable to create certificate public neither playground.

I end up with this error **The system cannot find the file specified.**

```
System.Security.Cryptography.X509Certificates.X509Certificate2Collection.LoadStoreFromBlob(Byte[] rawData, String password, UInt32 dwFlags, Boolean persistKeyContainers)
at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[]
rawData, String password, X509KeyStorageFlags keyStorageFlags)
at Mews.Eet.Dto.Certificate.ComputeKey()
at Mews.Eet.Dto.Certificate..ctor(String password, Byte[] data)
at Rotary.Web.Modules.EET.EetOrder..cctor()
```

What I discovered for now i, that on shared server is not user profile and certificate is creating in user folder, which is not accessible. And this error is thrown.

I tried modify Certificate.cs and add on line 14

`X509Certificate2 = new X509Certificate2(Data, Password, X509KeyStorageFlags.MachineKeySet);`

or combination of `X509KeyStorageFlags `but thid does not help.

My hosting provider tells me, that I must have physical server where this is working. But only for this issue , it is nonsense.

Do you have any experience with this error?

Thank you for your help

**Comment by jeancz** [comment]
I am pretty sure, that you need read/write rights into user profile (located at %APPDATA%\Microsoft\Crypto\RSA\User SID\) otherwise you will get this error.

It is matter security and therefor it is controled by OS.

**Comment by softak098** [comment]
If you have access to IIS configuration on hosting, modify application pool, advanced settings - enable "Load User Profile".

**Comment by pavelstaro** [comment]
I haven't access to IIS neither server, an that is why this error occur.

Another solution I came with is use certificate file instead byte array in Certificate constructor

, I'll try to simulate this, and publish result.

**Comment by jirihelmich** [comment]
Did #29 fix it for you?

**Comment by KaliCZ** [comment]
Closing - probably resolved over the time. For updates, see the [new repo](https://github.com/MewsSystems/fiscalizations).
