### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by vladimirlapacek** [MewsSystems/fiscalization-czechia#25]
Can you please add assembly signing using the strong name key? It is required when using your assembly as a dependency for a COM object.

Thanks!

**Comment by KaliCZ** [comment]
@vladimirlapacek We migrated the whole project to a [new repo](https://github.com/MewsSystems/fiscalizations) and it now targets .net standard. If this is still something that would help you, pls reopen the issue in the new repo.
