### ISSUE TITLE
Soap signature error

### ISSUE THREAD

**Issue by mmaganti** [MewsSystems/fiscalization-czechia#28]
I am using a production certificate and I am getting error 'Neplatny podpis SOAP zpravy' from server. It works fine with playground certificate. I have validated that there is no issue with the certificate. I am able to generate the FIK successfully using another library https://github.com/l-ra/openeet-net.  But using this library I consistently get the above error whether in both verification/production modes.

I have attached this file containing request SOAP body from both libraries
[requests.txt](https://github.com/MewsSystems/eet/files/1142554/requests.txt)

**Comment by jirihelmich** [comment]
Hi, you are not the first who is having an issue like this, but unfortunately, no matter what, we were unable to reproduce the issue. We use the library with over 40 different certificates, so does different companies, it's really weird.

Would you share the code how you integrate our library into your project?

**Comment by mmaganti** [comment]
Hi, thanks for quick response. Here is my code

if (File.Exists(certificateFile))
{
	string certificatePassword = GetCertificatePassword();

	string taxIdentificationNumber = GetTaxIdentificationNumber();
	string mandatingTaxIdentificationNumber = GetAltTaxIdentificationNumber();
	int businessId = GetBusinessIDNumber();
	bool isVerificationMode = IsVerificationMode();

	if (!string.IsNullOrWhiteSpace(mandatingTaxIdentificationNumber))
	{
		string temp = taxIdentificationNumber;
		taxIdentificationNumber = mandatingTaxIdentificationNumber;
		mandatingTaxIdentificationNumber = temp;
	}


	m_saleTime = request.SaleTime;
	m_locationTimeZone = TimeZoneInfo.FindSystemTimeZoneById(DateTimeZones.GetZone(location.TimeZone_ID).MS_TimeZone_Id);

	byte[] certData = null;
	try
	{
		certData = File.ReadAllBytes(certificateFile);
		if (certData?.Length > 0)
		{
			Certificate certificate = new Certificate(certificatePassword, certData);
			Identification identification = null;

			if (!string.IsNullOrEmpty(mandatingTaxIdentificationNumber))
			{
				identification = new Identification(
					taxPayerIdentifier: new TaxIdentifier(taxIdentificationNumber),
					mandatingTaxPayerIdentifier: new TaxIdentifier(mandatingTaxIdentificationNumber),
					registryIdentifier: new RegistryIdentifier(request.CashRegisterId),
					premisesIdentifier: new PremisesIdentifier(businessId),
					mandationType: MandationType.Section9Paragraph1,
					certificate: certificate);
			}
			else
			{
				identification = new Identification(
					taxPayerIdentifier: new TaxIdentifier(taxIdentificationNumber),
					registryIdentifier: new RegistryIdentifier(request.CashRegisterId),
					premisesIdentifier: new PremisesIdentifier(businessId),
					certificate: certificate);
			}

			decimal totalSaleAmount = request.TotalSaleAmount;
			decimal totalTaxAmount = request.TotalTaxAmount;
			decimal totalNonTaxableAmount = request.TotalNonTaxableAmount;
			decimal totalLiablePurchases = request.TotalLiablePurchases;
			decimal totalLoableTenderAmount = request.TotalLiableTenderAmount;

			totalSaleAmount = Math.Round(totalSaleAmount, 2);
			totalTaxAmount = Math.Round(totalTaxAmount, 2);
			totalNonTaxableAmount = Math.Round(totalNonTaxableAmount, 2);
			totalLiablePurchases = Math.Round(totalLiablePurchases, 2);
			totalLoableTenderAmount = Math.Round(totalLoableTenderAmount, 2);

			TaxRateItem standardTax = new TaxRateItem(
				new CurrencyValue(totalSaleAmount - totalTaxAmount), //zakl_dan1
				new CurrencyValue(totalTaxAmount), //dan1
				new CurrencyValue(0.0m)); //pouzit_zboz1

			Revenue revenue = new Revenue(
				gross: new CurrencyValue(totalSaleAmount), //celk_trzba
				accepted: new DateTimeWithTimeZone(request.SaleTime, m_locationTimeZone), //dat_trzby
				notTaxable: new CurrencyValue(totalNonTaxableAmount), //zakl_nepodl_dph
				deposit: new CurrencyValue(totalLiablePurchases), //urceno_cerp_zuct
				usedDeposit: new CurrencyValue(totalLoableTenderAmount), //cerp_zuct
				standardTaxRate: standardTax);

			RevenueRecord record = new RevenueRecord(
				identification: identification,
				revenue: revenue,
				billNumber: new BillNumber(request.InvoiveNumber.ToString()),
				isFirstAttempt: request.IsFirstAttempt);


			EetClient client = new EetClient(certificate, EetEnvironment.Production, TimeSpan.FromSeconds(timeout), new EetLogger(HandleEetLog));
			client.XmlMessageSerialized += XmlMessageSerialized;

			var response = client.SendRevenueAsync(record, isVerificationMode ? EetMode.Verification : EetMode.Operational);
			var result = response.Result;
			taxResponse = new TaxResponse();

			if (result.IsSuccess)
			{
				taxResponse.IsSuccess = true;
				taxResponse.TaxIdentificationNumber = result.Success.FiscalCode;
			}
			else
			{
				taxResponse.IsSuccess = false;
				taxResponse.Error = result.Error?.Reason?.Message;
			}
		}
	}                    
	catch (Exception ex)
	{
	}
}

**Comment by jirihelmich** [comment]
Could you maybe narrow it down to the failing case? E.g. is it the part using `Section9Paragraph1`?

**Comment by mmaganti** [comment]
In this case since I haven't defined the mandating tax number, it is not setting the mandationtype i.e. it is falling through the else block in the above code

**Comment by Linkula** [comment]
It may be off-topic, but I got the error ('Neplatny podpis SOAP zpravy') when trying to use a production certificate (issued for my employer) in Playground mode. When I used a playground certificate (provided on the "e-trzby.cz" site), everything worked fine. When I used the production certificate in production, there were no errors as well.

Hope it helps someone.

**Comment by KaliCZ** [comment]
We migrated the whole project to a [new repo](https://github.com/MewsSystems/fiscalizations). I believe the original issue is not present anymore. If anyone still has this issue, pls reopen in the new repo. 

As for the comment from Linkula, I'd say that's actually reasonable and not a bug :)
