### ISSUE TITLE
MandationType explanation

### ISSUE THREAD

**Issue by GrayLite** [MewsSystems/fiscalization-czechia#38]
Hi, could you please provide more info about this?

 public enum MandationType
    {
        Section8,
        Section9Paragraph1,
        Section9Paragraph2
    }

I can't find any information about it and your code testing only Section9Paragraph1 value here: 

   public Identification(TaxIdentifier **taxPayerIdentifier**, TaxIdentifier _mandatingTaxPayerIdentifier_, RegistryIdentifier registryIdentifier, PremisesIdentifier premisesIdentifier, MandationType mandationType, Certificate certificate)
            : this(**mandatingTaxPayerIdentifier**, mandationType == Dto.MandationType.Section9Paragraph1 ? _taxPayerIdentifier_ : null, registryIdentifier, premisesIdentifier, certificate, mandationType)
        {
        }

But there is a switch between taxPayerIdentifier and mandatingTaxPayerIdentifier in your constructor:

 private Identification(TaxIdentifier **taxPayerIdentifier**, TaxIdentifier _mandantingTaxPayerIdentifier_, RegistryIdentifier registryIdentifier, PremisesIdentifier premisesIdentifier, Certificate certificate, MandationType? mandationType = null)
       
Thank you in advance.

**Comment by marektresnak** [comment]
Hi, the term `mandation` is used to identify a situation where you report payments on behalf of somebody else. There are several types different types of mandation, all described in the Czech law about EET: https://www.podnikatel.cz/zakony/zakon-o-evidenci-trzeb/uplne/ (§8, §9 (1, 2)).

Depending on the type of the situation, you should either specify tax identifier of the seller and the mandating party (for §8 and §9 (2)), or specify only one of them (§9 (1)).

More examples can be found here: 
https://www.etrzby.cz/assets/cs/prilohy/Archiv/Priklady_datove_zpravy_I-v2.pdf
https://www.etrzby.cz/assets/cs/prilohy/Archiv/Priklady_datove_zpravy_II-v2.pdf

I can't provide english description as there doesn't seem to be any. But hope this helps.
