### ISSUE TITLE
Response signature verification

### ISSUE THREAD

**Issue by jirihelmich** [MewsSystems/fiscalization-czechia#8]
If a response is a valid success, it should be signed by the certificate of EET. Verify the signature. As the process is performance consuming and not really reliable, make it an optional feature.

via @todvora (thx):
>  K ověření revokace existují dva způsoby - CRL (certificate revocation lists) nebo OCSP (Online Certificate Status Protocol). I.CA poskytuje v tomto případě obě dvě možnosti.

**Comment by KaliCZ** [comment]
Moved to the new repo. https://github.com/MewsSystems/fiscalizations/issues/107
